import { useState } from 'react'
import Head from 'next/head'

import {api} from "../services/api"

export default function Index() {
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [office, setOffice] = useState('')
  const [phone, setPhone] = useState('')

  async function submit(e){
      e.preventDefault()
      const data = {nome: name, email: email, cargo: office, telefone: phone}
      try {
        const response = await api.post('/create', data)
      } catch (error) {
        console.log(error)
      }
  }

  return (
    <>
      <Head>
        <title>Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"/>
      </Head>
      <div class="background-home d-flex justify-content-center align-items-center flex-column">
          <div class="div-moura">
            <img src="moura.png" class="img-fluid logo-moura" />
          </div>

          <form id="formulario-home" class="d-flex flex-column" onSubmit={submit}>
            <div id='div-formulario-home' class="d-flex flex-column">
              <input type="text" class="mt-5 form-control-lg rounded-pill" placeholder="Nome" onChange={(e) => setName(e.target.value)}/>
              <input type="email" class="mt-3 form-control-lg rounded-pill" placeholder="E-mail" onChange={(e) => setEmail(e.target.value)} />
              <input type="tel" pattern="[0-9] {2,5,4}" class="mt-3 form-control-lg rounded-pill" placeholder="Telefone" onChange={(e) => setPhone(e.target.value)} />
              <input type="text" class="mt-3 form-control-lg rounded-pill" placeholder="Cargo" onChange={(e) => setOffice(e.target.value)} />
            </div>
            <input type="submit" class="mt-3 btn btn-warning rounded-pill btn-lg" value="Cadastrar" />
          </form>
          
          <a class="mt-3 btn btn-primary rounded" href="/listCard"><i class="bi bi-qr-code fs-1"></i></a>
      </div>
    </>
  )
}
